### ISSUE TITLE
Introduce netmap support on FreeBSD and Linux

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#116]
Because netmap can work without any licenses on huge speeds!

**Comment by pavel-odintsov** [comment]
https://www.freebsd.org/cgi/man.cgi?query=netmap&sektion=4

**Comment by dimsua** [comment]
on Linux too?

**Comment by pavel-odintsov** [comment]
It's very unstable and strange on Linux :(

You could look at this: https://code.google.com/p/netmap/issues/detail?id=30

**Comment by pavel-odintsov** [comment]
I have finished some test and support for Linux will be added to!

**Comment by pavel-odintsov** [comment]
We have compete support of netmap for Linux and FreeNSD since this commit: https://github.com/FastVPSEestiOu/fastnetmon/commit/0cfcd10db7e1199770c985a4d77bb9525c29a22c
