### ISSUE TITLE
Problems with the script installation fastnetmon_install.pl

### ISSUE THREAD

**Issue by gusilva** [FastVPSEestiOu/fastnetmon#120]
I am not able to install the FastNetMon on my debian environment. 

I am getting the following errors:

"/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:29:23: error: pfring_zc.h: No such file or directory
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:85: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:86: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:87: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:88: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:89: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:90: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:91: error: expected constructor, destructor, or type conversion before ‘*’ token
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp: In function ‘std::string get_pf_ring_stats()’:
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:261: error: ‘pfring_zc_stat’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:261: error: expected ‘;’ before ‘stats’
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:263: error: ‘inzq’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:263: error: ‘stats’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:263: error: ‘pfring_zc_stats’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:289: error: expected ‘;’ before ‘outq_stats’
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:291: error: ‘outzq’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:291: error: ‘outq_stats’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp: At global scope:
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:443: error: ‘pfring_zc_pkt_buff’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:443: error: ‘pkt_handle’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:443: error: ‘pfring_zc_queue’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:443: error: ‘in_queue’ was not declared in this scope
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:443: error: expected primary-expression before ‘void’
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:443: error: initializer expression list treated as compound expression
/usr/src/fastnetmon/pfring_plugin/pfring_collector.cpp:443: error: expected ‘,’ or ‘;’ before ‘{’ token
make[2]: *** [CMakeFiles/pfring_plugin.dir/pfring_plugin/pfring_collector.cpp.o] Error 1
make[1]: *** [CMakeFiles/pfring_plugin.dir/all] Error 2
make: *** [all] Error 2
Can't build fastnetmon! at fastnetmon_install.pl line 170."

Environment:
Description:    Debian GNU/Linux 6.0.10 (squeeze)
Release:        6.0.10
Codename:       squeeze

**Comment by pavel-odintsov** [comment]
Hello!

I will check this issue and answer you shortly. 

Thank you!

**Comment by pavel-odintsov** [comment]
Fixed in https://github.com/FastVPSEestiOu/fastnetmon/commit/8dd46cf313505492963494b3deaef6b3ee0e5c9f

If you want PF_RING ZC support please try to build SVN version of PF_RING from there: svn co https://svn.ntop.org/svn/ntop/trunk/PF_RING/

If you need only vanilla PF_RING, please do following:
```bash
cd /usr/src/fastnetmon
git pull
cd build
cmake ..
make
```

**Comment by gusilva** [comment]
Work like a charm!!!! Tks Pavel!

**Comment by pavel-odintsov** [comment]
Welcome :)
