### ISSUE TITLE
Can't use a lower ban_time than 600 seconds

### ISSUE THREAD

**Issue by Phinitris** [FastVPSEestiOu/fastnetmon#129]
We can't use a lower ban_time than 600 seconds, because the method cleanup_ban_list is only
called every 600 seconds due to wait/sleep.
Ban times lower than 600 seconds won't take effect.

**Comment by pavel-odintsov** [comment]
Thanks!

Fixed it https://github.com/FastVPSEestiOu/fastnetmon/commit/34806ba5becd3769635875aed38e8ea702ac122f please try!
