### ISSUE TITLE
Segmenation Fault

### ISSUE THREAD

**Issue by leapswitch** [FastVPSEestiOu/fastnetmon#177]
Hello,
I am getting a segmentation fault while running Fastnetmon.

# /opt/fastnetmon/fastnetmon

^CSegmentation fault (core dumped)

~]# gdb /opt/fastnetmon/fastnetmon core.27463 
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-75.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/fastnetmon/fastnetmon...(no debugging symbols found)...done.

warning: exec file is newer than core file.
[New Thread 27468]
[New Thread 27464]
[New Thread 27463]
[New Thread 27466]
[New Thread 27465]
[New Thread 27467]
Missing separate debuginfo for 
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/54/74f0d8daf3d6177e2c4b06f3892745cb43b4d5
Reading symbols from /usr/lib64/libboost_thread-mt.so.5...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libboost_thread-mt.so.5
Reading symbols from /usr/lib64/libboost_regex-mt.so.5...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libboost_regex-mt.so.5
Reading symbols from /usr/lib64/libboost_system-mt.so.5...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libboost_system-mt.so.5
Reading symbols from /usr/lib64/liblog4cpp.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/liblog4cpp.so.4
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /usr/lib64/libpcap.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libpcap.so.1
Reading symbols from /usr/lib64/libstdc++.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libstdc++.so.6
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/librt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/librt.so.1
Reading symbols from /usr/lib64/libicuuc.so.42...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libicuuc.so.42
Reading symbols from /usr/lib64/libicui18n.so.42...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libicui18n.so.42
Reading symbols from /lib64/libnsl.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnsl.so.1
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /usr/lib64/libicudata.so.42...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libicudata.so.42
Core was generated by `/opt/fastnetmon/fastnetmon'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004244bc in process_packet(simple_packet&) ()
Missing separate debuginfos, use: debuginfo-install boost-regex-1.41.0-25.el6.centos.x86_64 boost-system-1.41.0-25.el6.centos.x86_64 boost-thread-1.41.0-25.el6.centos.x86_64 glibc-2.12-1.149.el6_6.7.x86_64 libgcc-4.4.7-11.el6.x86_64 libicu-4.2.1-9.1.el6_2.x86_64 libpcap-1.4.0-1.20130826git2dbcaa1.el6.x86_64 libstdc++-4.4.7-11.el6.x86_64 log4cpp-1.0-13.el6_5.1.x86_64
(gdb) bt
#0  0x00000000004244bc in process_packet(simple_packet&) ()
#1  0x0000000000442285 in process_netflow_packet_v5(unsigned char*, unsigned int) ()
#2  0x000000000044477d in process_netflow_packet(unsigned char*, unsigned int) ()
#3  0x000000000044514d in start_netflow_collection(void (*)(simple_packet&)) ()
#4  0x00007f39587fad47 in thread_proxy () from /usr/lib64/libboost_thread-mt.so.5
#5  0x00007f3957ea69d1 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f39572138fd in clone () from /lib64/libc.so.6

**Comment by pavel-odintsov** [comment]
Hello!

Could you share pcap file with traffic dump? You could email it me directly: pavel.odintsov@gmail.com

**Comment by pavel-odintsov** [comment]
You could collect dump with this command:
```bash
tcpdump -w netflow_dump.pcap -n 'udp dst port 2055' 
```

**Comment by pavel-odintsov** [comment]
And please provide complete log from /var/log/fastnetmon.log

**Comment by pavel-odintsov** [comment]
Fixed in private conversation! :)
