### ISSUE TITLE
ExaBGP integration improvement

### ISSUE THREAD

**Issue by thomas-mangin** [FastVPSEestiOu/fastnetmon#206]
Hello, This seems a more elegant way to perform the 'PIPE trick'
run /bin/socat stdin unix-listen:/var/run/exabgp;

Taken from https://github.com/job/irrexplorer/blob/master/exabgp.conf

**Comment by pavel-odintsov** [comment]
Wow! Awesome! I will add this trick to my manuals shortly! :)

**Comment by thomas-mangin** [comment]
Leaving your way would not harm for people who can not install socat

**Comment by pavel-odintsov** [comment]
Well, I checked it and it did not work for my case because it uses unix domain socket. When I changed unix-socket to pipe no data saw on ExaBGP side :( But I will try to do my task with it.

Btw, when working with tail and mkfifo I found very interesting behavior of ExaBGP:
```bash
ps aux|grep exabg
root      9995  0.0  0.0  52644 14708 ?        S    23:00   0:00 /usr/bin/python /usr/local/bin/exabgp /etc/exabgp_blackhole.conf
root      9996  0.0  0.0   4328   864 ?        S    23:00   0:00 /bin/sh /etc/exabgp/exabgp_pipe_provider.sh
root      9999  0.0  0.0   5800  1296 ?        S    23:00   0:00 tail -f /var/run/exabgp.cmd
root     10073  0.0  0.0  12660  1600 pts/0    S+   23:03   0:00 grep exabg
```

I emitted kill command to ExaBGP:
```bash
kill 9995
```

But child of script process was not killed:
```bash
ps aux|grep exabg
root      9999  0.0  0.0   5800  1296 ?        S    23:00   0:00 tail -f /var/run/exabgp.cmd
root     10086  0.0  0.0  12656  1624 pts/0    R+   23:05   0:00 grep exabg
```

**Comment by pavel-odintsov** [comment]
Yep, I found good params for socat for my case: ```run /usr/bin/socat stdout pipe:/var/run/exabgp.cmd``` and updated manuals (and save old fashioned way): https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/EXABGP_INTEGRATION.md Now it becomes much times simpler than ever! Thank you so much!

**Comment by pavel-odintsov** [comment]
Heh, I tried to kill ExaBGP with socat:
```bash
 ps aux|grep exa
root     10252  0.0  0.0  52644 14680 ?        S    23:18   0:00 /usr/bin/python /usr/local/bin/exabgp /etc/exabgp_blackhole.conf
root     10253  0.0  0.0  19628  1652 ?        S    23:18   0:00 /usr/bin/socat stdout pipe:/var/run/exabgp.cmd
root     10315  0.0  0.0  12656  1604 pts/0    R+   23:24   0:00 grep exa

kill 10252
```

And everything killed correctly:
```bash
ps aux|grep exa
root     10319  0.0  0.0  12656  1604 pts/0    S+   23:24   0:00 grep exa
```

Looks like problem could arrive when spawned process have a child.

**Comment by thomas-mangin** [comment]
Yes, it depends how they fork the child ....

**Comment by pavel-odintsov** [comment]
Hello, Thomas!

In this case it's very simple child process:
```
```#!/bin/sh
FIFO="/var/run/exabgp.cmd"

rm -f $FIFO
mkfifo $FIFO
tail -f $FIFO
```

So, should I create bug for it in ExaBGP or it's feature?

**Comment by thomas-mangin** [comment]
It is the way bash/shells works :p 
You should try this version where exec replace the bash by tail.

```
#!/bin/sh
FIFO="/var/run/exabgp.cmd"

rm -f $FIFO
mkfifo $FIFO
exec tail -f $FIFO
```

so you do not have

```
exabgp
 \_ bash
      \_ tail
```

but 

```
exabgp
 \_ tail
```

**Comment by pavel-odintsov** [comment]
Heh, Nice explanation. Thank you! Thus, socat implemented and we could close ticket :)

**Comment by thomas-mangin** [comment]
It is also possible to trap the SIGTERM ( and other signals and have them propagated )
https://www.google.co.uk/search?q=propagate+signal+in+shell+script

**Comment by pavel-odintsov** [comment]
Very interesting article. Thanks!
