### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [FastVPSEestiOu/fastnetmon#213]
I would like to point out that identifiers like "[`_FAST_LIBRARY_H`](https://github.com/FastVPSEestiOu/fastnetmon/blob/ef5d5c4f52e7e6e638dbc37e0fa5b3e784eddf2c/src/fast_library.h#L1)" and "[`__IPFIX_RFC_H__`](https://github.com/FastVPSEestiOu/fastnetmon/blob/4a06fec2cde0c6a8274096d8114f34c65fcfd1fd/src/ipfix_rfc.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by pavel-odintsov** [comment]
Hello!

Not a big deal, I could change they.

**Comment by pavel-odintsov** [comment]
Fixed: https://github.com/FastVPSEestiOu/fastnetmon/commit/19d0ee48dfa45f80e0f08e2cc48b4b7c71ea3884 

Thank you so much!

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/FastVPSEestiOu/fastnetmon/blob/96f3c85909164aab81c8e885cf0565470ab97c51/src/fastnetmon_packet_parser.h#L1 "More update candidates?") left over?

**Comment by pavel-odintsov** [comment]
Just a second, I will fix all code :)

**Comment by pavel-odintsov** [comment]
Fixed completely.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/FastVPSEestiOu/fastnetmon/commit/c5d9fbec4c855f9102b23295e3243c2401118dc5 "Deletion of underscores in include guards").
