### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [FastVPSEestiOu/fastnetmon#214]
Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [New_Prefix2](https://github.com/FastVPSEestiOu/fastnetmon/blob/0bbe244aa05e77b8f481ec75784db3d0154785b8/src/libpatricia/patricia.c#L183)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "Signal management") ⇒ [main](https://github.com/FastVPSEestiOu/fastnetmon/blob/1bab717ce8845ba3df3660dfe24967347517b44a/src/fastnetmon.cpp#L1664)

**Comment by pavel-odintsov** [comment]
Fixed in my code. But patricia is an external library and I want to replace it soon. Thank you!

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by pavel-odintsov** [comment]
Very hard question. My code is enough complex but it works really well and I haven't time for so big changes.

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/FastVPSEestiOu/fastnetmon/blob/77454070e995bd2ef51f069ba363502434daba76/src/fastnetmon.cpp#L1279 "Another update candidate in recalculate_speed()?") left over?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](http://aspectc.net/ac_tutorial.html#reusablemachecking "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk
