### ISSUE TITLE
BGP flow spec interface for firewall

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#217]
https://github.com/Exa-Networks/exabgp/wiki/Controlling-ExaBGP-:-API-for-received-messages

**Comment by thomas-mangin** [comment]
Do not trust this documentation as it is surely out of date in quite a few places .. Feel free to update if you see something wrong and let me know if you need anything .

**Comment by pavel-odintsov** [comment]
Thanks for suggestion! I will be very careful with ExaBGP docs! :)

**Comment by thomas-mangin** [comment]
Feel free to correct the document tho :stuck_out_tongue_winking_eye:

**Comment by pavel-odintsov** [comment]
We could use this syntax for enable flow spec announce:
```bash
self.wfile.write(' example: withdraw flow route {\\n match {\\n source 10.0.0.1/32;\\n destination 1.2.3.4/32;\\n }\\n then {\\n discard;\\n }\\n }\\n\n')
```

**Comment by pavel-odintsov** [comment]
Implemented :) iptables/ipfw interface have moved to separate project: https://github.com/pavel-odintsov/FlowACL
