### ISSUE TITLE
FreeBSD_port missing conf.sample

### ISSUE THREAD

**Issue by dlyserg** [FastVPSEestiOu/fastnetmon#247]
[100%] Built target fastnetmon
===>  Staging for fastnetmon-1.1.2
===>   Generating temporary packing list
[  9%] Built target example_plugin
[ 18%] Built target patricia
[ 27%] Built target fast_library
[ 36%] Built target ipfix_rfc
[ 45%] Built target fastnetmon_packet_parser
[ 54%] Built target sflow_plugin
[ 63%] Built target netflow_plugin
[ 72%] Built target pcap_plugin
[ 81%] Built target netmap_plugin
[ 90%] Built target fastnetmon
[100%] Built target fastnetmon_client
Installing the project stripped...
-- Install configuration: "Release"
-- Installing: /usr/distr/fastnetmon/src/FreeBSD_port/work/stage/usr/local/bin/fastnetmon
-- Set runtime path of "/usr/distr/fastnetmon/src/FreeBSD_port/work/stage/usr/local/bin/fastnetmon" to "/usr/local/lib"
-- Installing: /usr/distr/fastnetmon/src/FreeBSD_port/work/stage/usr/local/bin/fastnetmon_client
/bin/mv /usr/distr/fastnetmon/src/FreeBSD_port/work/stage/usr/local/etc/fastnetmon.conf  /usr/distr/fastnetmon/src/FreeBSD_port/work/stage/usr/local/etc/fastnetmon.conf.sample
mv: rename /usr/distr/fastnetmon/src/FreeBSD_port/work/stage/usr/local/etc/fastnetmon.conf to /usr/distr/fastnetmon/src/FreeBSD_port/work/stage/usr/local/etc/fastnetmon.conf.sample: No such file or directory
*** [post-install] Error code 1

Stop in /usr/distr/fastnetmon/src/FreeBSD_port.
*** [stage] Error code 1

Stop in /usr/distr/fastnetmon/src/FreeBSD_port.

**Comment by pavel-odintsov** [comment]
Hello!

Port maintainer will look at this shortly.

**Comment by AMDmi3** [comment]
Update your source. That was fixed in e578d2def4db813302c74382009a428d9621e49a

**Comment by pavel-odintsov** [comment]
AMDmi3, thanks a lot!
