### ISSUE TITLE
Seperate IP Addresses per Switch and sum [Graphite]

### ISSUE THREAD

**Issue by Phinitris** [FastVPSEestiOu/fastnetmon#267]
The Graphite integration is really cool. However it would be really nice,
if we could use different "namespaces" for each switch who is sending data via e.g. sFlow.
Like: fastnetmon.switch1.1_2_3_4.mbps and fastnetmon.switch1.mbps

**Comment by pavel-odintsov** [comment]
Hello!

Nice suggestion. But unfortunately, I can't track "source of data" for certain IP. Because in common case we could get data about same IP from multiple devices/sources (netflow+sflow+port mirror). 

But this case rally useful because sometimes we need execute actions according of switch or device where flow tracked.

**Comment by Phinitris** [comment]
Yeah. But anyway. It would be nice, if we could set the "namespace" in the configuration file.
This way, I can just start multiple fastnetmon instances via e.g. LXC and do it that way.
For the future we could implement multiple instances, therefore start multiple fastnetmon instances with config file parameter, like:

/opt/fastnetmon/fastnetmon --daemonize -c /etc/fastnetmon.conf

I will provide a patch for the first solution in the next days. It makes sense for me.

**Comment by pavel-odintsov** [comment]
Hello!

Nice idea. Namespace support have implemented for Graphite: https://github.com/FastVPSEestiOu/fastnetmon/commit/b45516126603c4a1572503e0c8d84f8fb546d5d9

Thanks for really useful ideas for toolkit! :)

**Comment by pavel-odintsov** [comment]
Create new ticket about custom path for config file.

**Comment by pavel-odintsov** [comment]
And second ticket https://github.com/FastVPSEestiOu/fastnetmon/issues/267#issuecomment-110034057 :)

**Comment by Phinitris** [comment]
Thanks ;) You're awesome. Keep it up :D

**Comment by pavel-odintsov** [comment]
Welcome! :)

**Comment by pavel-odintsov** [comment]
Ability to run multiple instances for FastNetMon implemented in: https://github.com/FastVPSEestiOu/fastnetmon/issues/270
