### ISSUE TITLE
CHMOD itself?

### ISSUE THREAD

**Issue by Keldo** [FastVPSEestiOu/fastnetmon#280]
I just installed this on an Ubuntu 12.04.5 Honey pot Server, it installed just fine but I had to make the monitor executable manually in order to make it work or else I would get a "Permission Denied" error.

Just for some Situation Awareness...

**Comment by pavel-odintsov** [comment]
Hello!

Installer should enable exec flag. Do you have any filesystems with noexec
flag? Could you share ldd fastnetmon output?

On Saturday, June 13, 2015, Scott aka: Keldo <notifications@github.com>
wrote:

> I just installed this on an Ubuntu 12.04.5 Honey pot Server, it installed
> just fine but I had to make the monitor executable manually in order to
> make it work or else I would get a "Permission Denied" error.
>
> Just for some Situation Awareness...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/280>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
Close this ticket. If problem still exists, please reopen it. Thank you!
