### ISSUE TITLE
Please translate Comments in Code to English

### ISSUE THREAD

**Issue by kmarcroft** [FastVPSEestiOu/fastnetmon#291]
Please do translate your comments within the code to the english language.
It helps to understand the code.

Thanks

**Comment by pavel-odintsov** [comment]
Hello!

I'm so sorry, I already fixed this issue with non english letters few months ago. 

There are only few files with russian language:
```bash
grep -HiR -Eo "[А-Яа-яЁё]*"|egrep -v 'Binary|git'  |sed 's/:/ /'|awk '{print $1}'|sort |uniq 
src/notify_about_attack.sh
src/pfring_plugin/pfring_collector.cpp
src/sflow_plugin/sflow_collector.cpp
src/tests/DATA_STRUCTURES.md
src/tests/ip_lookup.cpp
src/tests/long_prefix_match_unused_code.cpp
src/tests/sort_struct.cpp
```

And I fix they shortly.

**Comment by pavel-odintsov** [comment]
Thank you for feedback :) I fixed all non-english symbols there: https://github.com/FastVPSEestiOu/fastnetmon/commit/37cc38e75c53a440c08cdf1e707a1daf9fe79fd5

Contributors are welcome :)
