### ISSUE TITLE
Upgrade/Update proceedure

### ISSUE THREAD

**Issue by kmarcroft** [FastVPSEestiOu/fastnetmon#292]
Please do supply either a script or Howto, on how to update/upgrade fastnetmon.
Currently I can't see any script or documentation for this topic.

Thanks & Keep up the good work!

**Comment by pavel-odintsov** [comment]
Hello!

It's first enough popular and stable FastNetMon's version :) But I created some draft manual about update to next version here: https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/UPDATE.md

**Comment by pavel-odintsov** [comment]
Thanks you :)
