### ISSUE TITLE
Blackhole: add option to announce whole subnet AND /32 IP

### ISSUE THREAD

**Issue by robdn** [FastVPSEestiOu/fastnetmon#302]
At the moment system allows to announce a /32 or entire subnet with particular community.
Some upstream providers do not accept blackhole communities though.

It would be nice if the system would allow to announce /32 with specific community and its entire subnet with a different community. 

This solution would be useful, for example, to prepend entire network to upstreams who do not support blackhole community in order to get incoming traffic away from them for particular subnet, and announce /32 to upstreams who do support blackhole community to get the traffic filtered out. Thanks to this feature the attack could be fully filtered out before reaching the destination network.

Regards,
Dom

**Comment by pavel-odintsov** [comment]
Hello!

I will try to answer with good code to brilliant idea :)  All your requests implemented. 

Actually since this commit we could use different communities for subnet and host announce. Additionally we could announce host and subnet in same time.

I have very similar use case. My upstream XXX haven't  support for BGP blackhole and I should move subnet which under ongoing attack from it. 

Thank you!

If you have any ideas, please create new ticket or email me directly: pavel.odintsov@gmail.com

**Comment by robdn** [comment]
Thank you Pavel!
I was already about to rethink the wheel via notifications script :-).

Thank you ! 

Regards,
Dom

**Comment by pavel-odintsov** [comment]
Thats why I tried to do it ASAP :) Please switch to dev branch  https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/DEV_VERSION.md and check my code :) I will be very glad.

**Comment by robdn** [comment]
Pavel, ban action works just fine.
Unban action removes /32 route and then attempts to remove incorrect subnet route.

[INFO] ExaBGP announce message: withdraw route 0.0.0.0/0
[INFO] ExaBGP announce message: withdraw route 192.168.0.1/32

Could you fix, please :)?

**Comment by pavel-odintsov** [comment]
Hello!

Very strange.....  Could you send complete /var/log/fastnetmon.log to pavel.odintsov@gmail.com?

**Comment by pavel-odintsov** [comment]
Could you pull new code from Git and build it again? I have same issue from Maillist and it's fixed in recent commits.

**Comment by pavel-odintsov** [comment]
So this issue if definitely fixed and checked by multiple customers, please upgrade to latest Git version and feel free to ask me if you have any questions :)
