### ISSUE TITLE
При атаке было отправлено только письмо с уведомлением

### ISSUE THREAD

**Issue by Anito23** [FastVPSEestiOu/fastnetmon#306]
Сегодня ночью при входящей UDP атаке скриптом уведомления было отправлено только письмо. Блокировки на роутерах выполнены небыли. 

В логе fastnetmon видно, что был отработан код execute_ip_ban:

2015-06-27 02:53:02,261 [INFO] We run execute_ip_ban code with following params  in_pps: 178204 out_pps: 405 in_bps: 59790056 out_bps: 143968 and we decide it's incoming attack
2015-06-27 02:53:02,261 [INFO] Attack with direction: incoming IP: 5.101.118.205 Power: 178204
2015-06-27 02:53:02,261 [INFO] Call script for ban client: 5.101.118.205
2015-06-27 02:53:02,261 [INFO] Script for ban client is finished: 5.101.118.205
2015-06-27 03:25:13,655 [INFO] We will unban banned IP: 5.101.118.205 because it ban time 1900 seconds is ended
2015-06-27 03:25:13,655 [INFO] Call script for unban client: 5.101.118.205
2015-06-27 03:25:13,655 [INFO] Script for unban client is finished: 5.101.118.205

Так же, видно что второй запуск скрипта уведомления не был произведен. 

Сложилось ощущение, что при первом запуске скрипта уведомления, по какой то причине, ему был передан в качестве 4 параметра attack_details, а не ban. Хотя пришедшее письмо содержит текст stdin которое обычно отправляется при первом запуске скрипта уведомления:

IP: 5.101.118.205
Attack type: udp_flood
Initial attack power: 178204 packets per second
Peak attack power: 178204 packets per second
Attack direction: incoming
Attack protocol: udp
Total incoming traffic: 456 mbps
Total outgoing traffic: 1 mbps
Total incoming pps: 178204 packets per second
Total outgoing pps: 405 packets per second
Total incoming flows: 1018 flows per second
Total outgoing flows: 0 flows per second
Average incoming traffic: 456 mbps

**Comment by pavel-odintsov** [comment]
Не, судя по всем просто не успело собрать отпечаток атаки и поэтому не дернуло второй скрипт.

**Comment by Anito23** [comment]
После введения полного логирования действий скрипта уведомления, обнаружилось что при первом запуске скрипта уведомления ему передается в качестве аргумента action - attack_details. А при повторном запуске уже сам ban. Так как второго запуска не было сделано в ситуации описанной в первом сообщении, не были выполнены блокировки на роутерах. 

Далее приведен текст лога отработки скрипта уведомления сегодняшних двух атак: 

Jun 28 17:15:48 netflow logger[13880]: notify_about_attack.sh ip: 5.45.125.133, direction: incoming, pps: 108316, action: attack_details
Jun 28 17:15:48 netflow logger[13882]: notify_about_attack.sh Start attack details action
Jun 28 17:15:48 netflow logger[13889]: notify_about_attack.sh Sending second run mail about 5.45.125.133
Jun 28 17:15:48 netflow logger[13895]: notify_about_attack.sh Second run mail about 5.45.125.133 sent
Jun 28 17:15:48 netflow logger[13906]: notify_about_attack.sh ip: 5.45.125.133, direction: incoming, pps: 108316, action: ban
Jun 28 17:15:48 netflow logger[13908]: notify_about_attack.sh Start ban action
Jun 28 17:15:48 netflow logger[13915]: notify_about_attack.sh Full block
Jun 28 17:15:48 netflow logger[13917]: notify_about_attack.sh Sending first run mail about 5.45.125.133
Jun 28 17:15:48 netflow logger[13922]: notify_about_attack.sh Start blackholing 5.45.125.133 on router1
Jun 28 17:15:48 netflow logger[13927]: notify_about_attack.sh Start blackholing 5.45.125.133 on router2
Jun 28 17:15:48 netflow logger[13929]: notify_about_attack.sh First run mail about 5.45.125.133 sent
Jun 28 17:15:50 netflow logger[13937]: notify_about_attack.sh IP 5.45.125.133 blackholed on router2
Jun 28 17:15:56 netflow logger[13939]: notify_about_attack.sh IP 5.45.125.133 blackholed on router1
Jun 28 17:17:31 netflow logger[13968]: notify_about_attack.sh ip: 5.101.120.146, direction: incoming, pps: 106472, action: attack_details
Jun 28 17:17:31 netflow logger[13970]: notify_about_attack.sh Start attack details action
Jun 28 17:17:31 netflow logger[13977]: notify_about_attack.sh Sending second run mail about 5.101.120.146
Jun 28 17:17:31 netflow logger[13983]: notify_about_attack.sh Second run mail about 5.101.120.146 sent
Jun 28 17:17:32 netflow logger[13993]: notify_about_attack.sh ip: 5.101.120.146, direction: incoming, pps: 106472, action: ban
Jun 28 17:17:32 netflow logger[13995]: notify_about_attack.sh Start ban action
Jun 28 17:17:32 netflow logger[14002]: notify_about_attack.sh Full block
Jun 28 17:17:32 netflow logger[14004]: notify_about_attack.sh Sending first run mail about 5.101.120.146
Jun 28 17:17:32 netflow logger[14009]: notify_about_attack.sh Start blackholing 5.101.120.146 on router1
Jun 28 17:17:32 netflow logger[14015]: notify_about_attack.sh Start blackholing 5.101.120.146 on router2
Jun 28 17:17:32 netflow logger[14016]: notify_about_attack.sh First run mail about 5.101.120.146 sent
Jun 28 17:17:34 netflow logger[14021]: notify_about_attack.sh IP 5.101.120.146 blackholed on router2
Jun 28 17:17:41 netflow logger[14026]: notify_about_attack.sh IP 5.101.120.146 blackholed on router1

**Comment by Anito23** [comment]
Из лога самого скрипт из fastnetmon.log видно, что в 17:17:31 должен был запуститься бан, а в 17:17:32 attack details.

2015-06-28 17:17:31,496 [INFO] We run execute_ip_ban code with following params  in_pps: 106472 out_pps: 4494 in_bps: 6395105 out_bps: 275945 and we decide it's incoming attack
2015-06-28 17:17:31,496 [INFO] Attack with direction: incoming IP: 5.101.120.146 Power: 106472
2015-06-28 17:17:31,497 [INFO] Call script for ban client: 5.101.120.146
2015-06-28 17:17:31,497 [INFO] Script for ban client is finished: 5.101.120.146
2015-06-28 17:17:32,470 [INFO] Attack with direction: incoming IP: 5.101.120.146 Power: 106472 traffic sample collected
2015-06-28 17:17:32,470 [INFO] Call script for notify about attack details for: 5.101.120.146
2015-06-28 17:17:32,470 [INFO] Script for notify about attack details is finished: 5.101.120.146

**Comment by pavel-odintsov** [comment]
Мда, спасибо! Так и было, ban и attack_details были перепутаны в коде. Уж не знаю, как я такое учудил.

Исправлено: https://github.com/FastVPSEestiOu/fastnetmon/commit/72c09bc6b1c0d2c1791c41170c331117aa3e3c22
