### ISSUE TITLE
is there any method to add customization for attack detection and midigration ? 

### ISSUE THREAD

**Issue by linyutsung6502** [FastVPSEestiOu/fastnetmon#332]
I evaluate this open source to prevent ddos attack, but I found it doesn't provide DNS flood attack detection. If using plugin or rule-based,  it would be more scalable and flexible.

**Comment by pavel-odintsov** [comment]
Hello!

There are so much DNS flood attack types. What are you interested for? Could you provide example pcap or tcpdump output for they?

**Comment by linyutsung6502** [comment]
hi pavel,
I already have your answer in google forum, thanks.
