### ISSUE TITLE
Is there any tutorial or instructions how to run and use fastnetmon?

### ISSUE THREAD

**Issue by Drewshg312** [FastVPSEestiOu/fastnetmon#333]
Hi!
Is there any tutorial or instructions how to run use fastnetmon?
Thank you!

**Comment by pavel-odintsov** [comment]
Hello!

You could use this page as reference: https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/INSTALL.md

**Comment by Drewshg312** [comment]
thank you!

**Comment by pavel-odintsov** [comment]
Welcome!
