### ISSUE TITLE
Examples of setting up alert email ?

### ISSUE THREAD

**Issue by tonytan4ever** [FastVPSEestiOu/fastnetmon#350]
Hi Pavel:
    Can you provide a quick example of configuration and set up a alert email notification as in the README file ?
    Thanks a lot!

**Comment by pavel-odintsov** [comment]
Hi!

Could you try this manual https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/INSTALL.md?

**Comment by pavel-odintsov** [comment]
If you have any questions, please ask fastnetmon@googlegroups.com :)
