### ISSUE TITLE
FreeBSD ndpi_api.h libndpi

### ISSUE THREAD

**Issue by bolt17** [FastVPSEestiOu/fastnetmon#358]
Hello,

here is the error from manual installation:

[root@dosdetect1 /usr/local/src/fastnetmon/src/build]# make
Scanning dependencies of target example_plugin
[  7%] Building CXX object CMakeFiles/example_plugin.dir/example_plugin/example_collector.cpp.o
Linking CXX static library libexample_plugin.a
[  7%] Built target example_plugin
Scanning dependencies of target fast_dpi
[ 15%] Building CXX object CMakeFiles/fast_dpi.dir/fast_dpi.cpp.o
In file included from /usr/local/src/fastnetmon/src/fast_dpi.cpp:1:
/usr/local/src/fastnetmon/src/fast_dpi.h:5:10: fatal error: 'libndpi/ndpi_api.h' file not found
#include "libndpi/ndpi_api.h"
         ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/local/src/fastnetmon/src/build
*** Error code 1

Stop.
make[1]: stopped in /usr/local/src/fastnetmon/src/build
*** Error code 1

Stop.
make: stopped in /usr/local/src/fastnetmon/src/build

Where can i get 'libndpi/ndpi_api.h ?

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately new code is not well tested in FreeBSD. Please try to use
port with 1.1.2 version:
https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/FreeBSD_INSTALL.md


On Wed, Aug 5, 2015 at 2:58 PM, bolt17 <notifications@github.com> wrote:

> Hello,
>
> here is the error from manual installation:
>
> [root@dosdetect1 /usr/local/src/fastnetmon/src/build]# make
> Scanning dependencies of target example_plugin
> [ 7%] Building CXX object
> CMakeFiles/example_plugin.dir/example_plugin/example_collector.cpp.o
> Linking CXX static library libexample_plugin.a
> [ 7%] Built target example_plugin
> Scanning dependencies of target fast_dpi
> [ 15%] Building CXX object CMakeFiles/fast_dpi.dir/fast_dpi.cpp.o
> In file included from /usr/local/src/fastnetmon/src/fast_dpi.cpp:1:
> /usr/local/src/fastnetmon/src/fast_dpi.h:5:10: fatal error:
> 'libndpi/ndpi_api.h' file not found
> #include "libndpi/ndpi_api.h"
> ^
> 1 error generated.
> *** Error code 1
>
> Stop.
> make[2]: stopped in /usr/local/src/fastnetmon/src/build
> *** Error code 1
>
> Stop.
> make[1]: stopped in /usr/local/src/fastnetmon/src/build
> *** Error code 1
>
> Stop.
> make: stopped in /usr/local/src/fastnetmon/src/build
>
> Where can i get 'libndpi/ndpi_api.h ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/358>.
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
I have upgraded install script and you could install recent version on FreeBSD: https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/FreeBSD_INSTALL.md
