### ISSUE TITLE
Automated install script not working on CentOS

### ISSUE THREAD

**Issue by mail3dexter** [FastVPSEestiOu/fastnetmon#359]
[root@FastNetMon tmp]# sudo perl fastnetmon_install.pl
Install PF_RING dependencies with package manager
http://mirrors.easynews.com//linux/centos/6.6/extras/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirrors.easynews.com//linux/centos/6.6/extras/x86_64/repodata/repomd.xml: (28, 'connect() timed out!')
Trying other mirror.
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA1 Signature, key ID c105b9de: NOKEY
Importing GPG key 0xC105B9DE:
 Userid : CentOS-6 Key (CentOS 6 Official Signing Key) <centos-6-key@centos.org>
 Package: centos-release-6-4.el6.centos.10.x86_64 (@anaconda-CentOS-201303050102.x86_64/6.5)
 From   : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
Download PF_RING 6.0.3 sources
Unpack PF_RING
Build PF_RING kernel module
Unload PF_RING if it was installed earlier
Load PF_RING module into kernel
PF_RING loaded correctly
Build PF_RING lib
ar: creating libpfring.a
Create library symlink
Add pf_ring to ld.so.conf
Install FastNetMon dependency list
Clone FastNetMon repo
In file included from /usr/src/fastnetmon/src/fast_dpi.cpp:1:
/usr/src/fastnetmon/src/fast_dpi.h:5:30: error: libndpi/ndpi_api.h: No such file or directory
/usr/src/fastnetmon/src/fast_dpi.cpp:3: error: ‘ndpi_log_level_t’ has not been declared
/usr/src/fastnetmon/src/fast_dpi.cpp: In function ‘void debug_printf(u_int32_t, void*, int, const char*, ...)’:
/usr/src/fastnetmon/src/fast_dpi.cpp:4: error: ‘va_list’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:4: error: expected ‘;’ before ‘va_ap’
/usr/src/fastnetmon/src/fast_dpi.cpp:5: error: aggregate ‘tm result’ has incomplete type and cannot be defined
/usr/src/fastnetmon/src/fast_dpi.cpp:10: error: ‘time’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:12: error: ‘va_ap’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:12: error: ‘va_start’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:23: error: ‘memset’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:24: error: ‘localtime_r’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:24: error: ‘strftime’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:25: error: ‘vsnprintf’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:27: error: ‘snprintf’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:28: error: ‘printf’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:29: error: ‘stdout’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:29: error: ‘fflush’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:31: error: ‘va_end’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp: In function ‘ndpi_detection_module_struct* init_ndpi()’:
/usr/src/fastnetmon/src/fast_dpi.cpp:38: error: ‘ndpi_init_detection_module’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:45: error: ‘NDPI_PROTOCOL_BITMASK’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:45: error: expected ‘;’ before ‘all’
/usr/src/fastnetmon/src/fast_dpi.cpp:47: error: ‘all’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:47: error: ‘NDPI_BITMASK_SET_ALL’ was not declared in this scope
/usr/src/fastnetmon/src/fast_dpi.cpp:48: error: ‘ndpi_set_protocol_detection_bitmask2’ was not declared in this scope
make[2]: *** [CMakeFiles/fast_dpi.dir/fast_dpi.cpp.o] Error 1
make[1]: *** [CMakeFiles/fast_dpi.dir/all] Error 2
make: *** [all] Error 2
Can't build fastnetmon! at fastnetmon_install.pl line 608.

Sorry If i missed something. I am new to linux environment and new to GitHub.

**Comment by pavel-odintsov** [comment]
Hello!

Looks like you have cloned master branch and run installer.

But for your case I recommends to use installer from Github manual.

On Wednesday, August 5, 2015, mail3dexter <notifications@github.com> wrote:

> [root@FastNetMon tmp]# sudo perl fastnetmon_install.pl
> Install PF_RING dependencies with package manager
>
> http://mirrors.easynews.com//linux/centos/6.6/extras/x86_64/repodata/repomd.xml:
> [Errno 12] Timeout on
> http://mirrors.easynews.com//linux/centos/6.6/extras/x86_64/repodata/repomd.xml:
> (28, 'connect() timed out!')
> Trying other mirror.
> warning: rpmts_HdrFromFdno: Header V3 RSA/SHA1 Signature, key ID c105b9de:
> NOKEY
> Importing GPG key 0xC105B9DE:
> Userid : CentOS-6 Key (CentOS 6 Official Signing Key)
> centos-6-key@centos.org
> <javascript:_e(%7B%7D,'cvml','centos-6-key@centos.org');>
> Package: centos-release-6-4.el6.centos.10.x86_64
> (@anaconda-CentOS-201303050102.x86_64/6.5)
> From : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
> Download PF_RING 6.0.3 sources
> Unpack PF_RING
> Build PF_RING kernel module
> Unload PF_RING if it was installed earlier
> Load PF_RING module into kernel
> PF_RING loaded correctly
> Build PF_RING lib
> ar: creating libpfring.a
> Create library symlink
> Add pf_ring to ld.so.conf
> Install FastNetMon dependency list
> Clone FastNetMon repo
> In file included from /usr/src/fastnetmon/src/fast_dpi.cpp:1:
> /usr/src/fastnetmon/src/fast_dpi.h:5:30: error: libndpi/ndpi_api.h: No
> such file or directory
> /usr/src/fastnetmon/src/fast_dpi.cpp:3: error: ‘ndpi_log_level_t’ has not
> been declared
> /usr/src/fastnetmon/src/fast_dpi.cpp: In function ‘void
> debug_printf(u_int32_t, void*, int, const char*, ...)’:
> /usr/src/fastnetmon/src/fast_dpi.cpp:4: error: ‘va_list’ was not declared
> in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:4: error: expected ‘;’ before ‘va_ap’
> /usr/src/fastnetmon/src/fast_dpi.cpp:5: error: aggregate ‘tm result’ has
> incomplete type and cannot be defined
> /usr/src/fastnetmon/src/fast_dpi.cpp:10: error: ‘time’ was not declared in
> this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:12: error: ‘va_ap’ was not declared
> in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:12: error: ‘va_start’ was not
> declared in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:23: error: ‘memset’ was not declared
> in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:24: error: ‘localtime_r’ was not
> declared in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:24: error: ‘strftime’ was not
> declared in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:25: error: ‘vsnprintf’ was not
> declared in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:27: error: ‘snprintf’ was not
> declared in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:28: error: ‘printf’ was not declared
> in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:29: error: ‘stdout’ was not declared
> in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:29: error: ‘fflush’ was not declared
> in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:31: error: ‘va_end’ was not declared
> in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp: In function
> ‘ndpi_detection_module_struct* init_ndpi()’:
> /usr/src/fastnetmon/src/fast_dpi.cpp:38: error:
> ‘ndpi_init_detection_module’ was not declared in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:45: error: ‘NDPI_PROTOCOL_BITMASK’
> was not declared in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:45: error: expected ‘;’ before ‘all’
> /usr/src/fastnetmon/src/fast_dpi.cpp:47: error: ‘all’ was not declared in
> this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:47: error: ‘NDPI_BITMASK_SET_ALL’ was
> not declared in this scope
> /usr/src/fastnetmon/src/fast_dpi.cpp:48: error:
> ‘ndpi_set_protocol_detection_bitmask2’ was not declared in this scope
> make[2]: *** [CMakeFiles/fast_dpi.dir/fast_dpi.cpp.o] Error 1
> make[1]: *** [CMakeFiles/fast_dpi.dir/all] Error 2
> make: *** [all] Error 2
> Can't build fastnetmon! at fastnetmon_install.pl line 608.
>
> Sorry If i missed something. I am new to linux environment and new to
> GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/359>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by mail3dexter** [comment]
Thanks for your prompt reply.
I had used the same installation script which was provided in this install.md : https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/INSTALL.md

wget https://raw.githubusercontent.com/FastVPSEestiOu/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
sudo perl fastnetmon_install.pl

**Comment by pavel-odintsov** [comment]
Thanks for fast answer, I will check this code shortly.

Could you try to install Git version:
wget
https://raw.githubusercontent.com/FastVPSEestiOu/fastnetmon/master/src/fastnetmon_install.pl
-Ofastnetmon_install.pl
sudo perl fastnetmon_install.pl --use-git-master

?

On Wed, Aug 5, 2015 at 9:58 PM, Mayur Patel <notifications@github.com>
wrote:

> Thanks for your prompt reply.
> I had used the same installation script which was provided in this
> install.md :
> https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/INSTALL.md
>
> wget
> https://raw.githubusercontent.com/FastVPSEestiOu/fastnetmon/master/src/fastnetmon_install.pl
> -Ofastnetmon_install.pl
> sudo perl fastnetmon_install.pl
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/359#issuecomment-128110021>
> .
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
I have found this bug. Please wait few seconds :)

**Comment by mail3dexter** [comment]
Worked for me :+1: Thank you very much.. Will test and let you know.
FYI, it gave me few warnings:
autoreconf: Leaving directory `.'
Package json-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-c' found
Package json-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-c' found
Package json-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-c' found
Package json-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-c' found
Build and install nDPI

Also, is there a Email script available on GitHub which can email same output as you have shown in this link : https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/ATTACK_REPORT_EXAMPLE.md

**Comment by pavel-odintsov** [comment]
I have fixed original issue: https://github.com/FastVPSEestiOu/fastnetmon/commit/76c6c8b45d71506d7f081a31af143daf1dcc423f 

It's related to very old git version in CentOS 6 but I found nice trick :)

**Comment by pavel-odintsov** [comment]
And I fixed issue with json-c: https://github.com/FastVPSEestiOu/fastnetmon/commit/45afb14d88d4fbe9555444a3f76bfe0c39cf36dc too :)
