### ISSUE TITLE
Can't build fastnetmon! error message

### ISSUE THREAD

**Issue by aleruri** [FastVPSEestiOu/fastnetmon#375]
Hi,

When trying to install fastnetmon in  a debian host I am getting the error "can't build fastnetmon! at fastnetmon_install pl line 925" error message. 

The scrip I am running is:

wget https://raw.githubusercontent.com/FastVPSEestiOu/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 

sudo perl fastnetmon_install.pl

Are you able to shed some light on this issue?

Regards,

Alex

**Comment by pavel-odintsov** [comment]
Hello!

Please share log file /tmp/fastnetmon_install.log

Thanks!

On Wednesday, August 19, 2015, aleruri <notifications@github.com> wrote:

> Hi,
>
> When trying to install fastnetmon in a debian host I am getting the error
> "can't build fastnetmon! at fastnetmon_install pl line 925" error message.
>
> The scrip I am running is:
>
> wget
> https://raw.githubusercontent.com/FastVPSEestiOu/fastnetmon/master/src/fastnetmon_install.pl
> -Ofastnetmon_install.pl
>
> sudo perl fastnetmon_install.pl
>
> Are you able to shed some light on this issue?
>
> Regards,
>
> Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/375>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by aleruri** [comment]
Hi Pavel,

Thanks for the prompt reply.

I am attaching the file /tmp/fastnetmon_install.log.

Regards,

Alex

On 19 August 2015 at 16:19, Pavel Odintsov <notifications@github.com> wrote:

> Hello!
>
> Please share log file /tmp/fastnetmon_install.log
>
> Thanks!
>
> On Wednesday, August 19, 2015, aleruri <notifications@github.com> wrote:
>
> > Hi,
> >
> > When trying to install fastnetmon in a debian host I am getting the error
> > "can't build fastnetmon! at fastnetmon_install pl line 925" error
> message.
> >
> > The scrip I am running is:
> >
> > wget
> >
> https://raw.githubusercontent.com/FastVPSEestiOu/fastnetmon/master/src/fastnetmon_install.pl
> > -Ofastnetmon_install.pl
> >
> > sudo perl fastnetmon_install.pl
> >
> > Are you able to shed some light on this issue?
> >
> > Regards,
> >
> > Alex
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/FastVPSEestiOu/fastnetmon/issues/375>.
> >
>
>
> --
> Sincerely yours, Pavel Odintsov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/375#issuecomment-132459593>
> .
>



-- 
[image: CEnet Transparent.png]
[image: Inline images 3] <http://gplus.to/CEnetAus>   [image: Inline images
6] <http://twitter.com/cenetaus>   [image: Inline images 5]
<http://www.linkedin.com/company/cenet---catholic-education-network>   [image:
Inline images 7] <http://www.youtube.com/user/CEnetAus>   [image: Inline
images 9] <http://www.facebook.com/CEnetAus>
*Alejandro Ruiz, M. Eng.*| *CEnet **Services Officer: **Network
Specialist/Team leader infrastructure and network teams*
BA. Electronics Engineering. CCNP, CCDP
Email\SIP: alejandro.ruiz@cenet.catholic.edu.au
A: Level 1, 2 Bond St, Bellambi NSW 2518
T: +61 2 4222 9311 | M: +61 434 578 976

**Comment by pavel-odintsov** [comment]
Hello!

GitHub do not support attaches :( Could you send it to me directly
pavel.odintsov@gmail.com?

On Wednesday, August 19, 2015, aleruri <notifications@github.com> wrote:

> Hi Pavel,
>
> Thanks for the prompt reply.
>
> I am attaching the file /tmp/fastnetmon_install.log.
>
> Regards,
>
> Alex
>
> On 19 August 2015 at 16:19, Pavel Odintsov <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Hello!
> >
> > Please share log file /tmp/fastnetmon_install.log
> >
> > Thanks!
> >
> > On Wednesday, August 19, 2015, aleruri <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Hi,
> > >
> > > When trying to install fastnetmon in a debian host I am getting the
> error
> > > "can't build fastnetmon! at fastnetmon_install pl line 925" error
> > message.
> > >
> > > The scrip I am running is:
> > >
> > > wget
> > >
> >
> https://raw.githubusercontent.com/FastVPSEestiOu/fastnetmon/master/src/fastnetmon_install.pl
> > > -Ofastnetmon_install.pl
> > >
> > > sudo perl fastnetmon_install.pl
> > >
> > > Are you able to shed some light on this issue?
> > >
> > > Regards,
> > >
> > > Alex
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/FastVPSEestiOu/fastnetmon/issues/375>.
> > >
> >
> >
> > --
> > Sincerely yours, Pavel Odintsov
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/FastVPSEestiOu/fastnetmon/issues/375#issuecomment-132459593
> >
> > .
> >
>
>
>
> --
> [image: CEnet Transparent.png]
> [image: Inline images 3] <http://gplus.to/CEnetAus> [image: Inline images
> 6] <http://twitter.com/cenetaus> [image: Inline images 5]
> <http://www.linkedin.com/company/cenet---catholic-education-network>
> [image:
> Inline images 7] <http://www.youtube.com/user/CEnetAus> [image: Inline
> images 9] <http://www.facebook.com/CEnetAus>
> *Alejandro Ruiz, M. Eng.*| *CEnet **Services Officer: **Network
> Specialist/Team leader infrastructure and network teams*
> BA. Electronics Engineering. CCNP, CCDP
> Email\SIP: alejandro.ruiz@cenet.catholic.edu.au
> <javascript:_e(%7B%7D,'cvml','alejandro.ruiz@cenet.catholic.edu.au');>
> A: Level 1, 2 Bond St, Bellambi NSW 2518
> T: +61 2 4222 9311 | M: +61 434 578 976
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/375#issuecomment-132461736>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
Hello :)

I have found this regression and fixed it. Please download new installer script and run it again. Thanks!
