### ISSUE TITLE
CentOS 6 install warnings

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#383]
```bash
Package 'GeoIP-devel' install failed with code 256
Package 'hiredis-devel' install failed with code 256
```

**Comment by pavel-odintsov** [comment]
So we install EPEL by default and this messages went away.

**Comment by robert1112** [comment]
Hi @pavel-odintsov  I got the code 256 with FRESH centos 7 on Google Cloud Platform. I update Centos 7 before installation and it failed to install EPEL.
```
Install EPEL repository for your system
Package 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm' install failed with code 256
Update package manager cache
```
So I have to pre-install EPEL before FastNetMon by running `sudo yum install epel-release `

And now installation can succeed. Thank you.

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for reporting it! Yes, they slightly changed process.
