### ISSUE TITLE
Install fastnetmon binary with apt-get instead of dpkg

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#386]
We could use it if we download package to /var/cache..

```bash
You can install it using apt-get install package_name. But first move your deb file to /var/cache/apt/archives/ directory. After executing this command, it will automatically download its dependencies.
```

**Comment by pavel-odintsov** [comment]
Implemented

**Comment by plajjan** [comment]
You could build a apt repo hosted at GitHub which is a bit nicer than just downloading .deb files. We are doing this for NIPAP. See the top level makefile and the "debrepo-*" targets for how to do this using reprepro.

**Comment by pavel-odintsov** [comment]
Yes, it will be next step. I should make better my current binary packages and then will offer repo :)
