### ISSUE TITLE
Вызов скрипта notify_script_path в течений атаки

### ISSUE THREAD

**Issue by mdpuma** [FastVPSEestiOu/fastnetmon#391]
Здравствуйте,

Было бы неплохо добавить возможность добавления выполнения скрипта из параметра notify_script_path раз в 30 секунд. Так получается что при определений атаки скрипт выполняется и параметры атаки записаны в сообщений в момент когда была зафиксирована, а в случае если полоса атаки повышается, об этом не будет известно.

Также это пригодилось бы для выполнения разных действий в зависимости от мощности атаки.

**Comment by pavel-odintsov** [comment]
Я думал об этом в несколько ином контексте, а именно в многопороговых конфигурациях. Когда 1 скрипт дергается когда выбито 100кппс, другой - когда 1 мппс итд итп.

Дергать скрипт нотификации задача затратная и если атак много, то вообще софт повиснуть может.

**Comment by mdpuma** [comment]
Думаю напишу скрипт который читает скорость атаки из stdin, чтобы не усложнять программу дополнительной опцией.

**Comment by pavel-odintsov** [comment]
Ага, но вы еще на тикет https://github.com/FastVPSEestiOu/fastnetmon/issues/62 подписывайтсь. Там похожая задача решается
