### ISSUE TITLE
Unable to compile with -DHWFILTER_LOCKING enabled

### ISSUE THREAD

**Issue by fargox** [FastVPSEestiOu/fastnetmon#395]
Hi,

i am unable to compile fastnetmon with the option -DHWFILTER_LOCKING enabled. I've installed pf_ring and using an Intel X520 card. So in theory the system should be compatible. Any ideas?

[ 33%] Built target patricia
[ 40%] Built target fast_library
[ 46%] Built target pfring_plugin
[ 53%] Built target fastnetmon_packet_parser
[ 60%] Built target sflow_plugin
[ 66%] Built target netmap_plugin
[ 73%] Built target ipfix_rfc
[ 80%] Built target netflow_plugin
[ 86%] Built target pcap_plugin
[ 93%] Building CXX object CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o
/usr/src/fastnetmon/src/fastnetmon.cpp: In function ‘void block_all_traffic_with_82599_hardware_filtering(std::string)’:
/usr/src/fastnetmon/src/fastnetmon.cpp:2952:13: error: ‘hw_filtering_rule’ was not declared in this scope
             hw_filtering_rule rule;
             ^
/usr/src/fastnetmon/src/fastnetmon.cpp:2953:13: error: ‘intel_82599_five_tuple_filter_hw_rule’ was not declared in this scope
             intel_82599_five_tuple_filter_hw_rule* ft_rule;
             ^
/usr/src/fastnetmon/src/fastnetmon.cpp:2953:52: error: ‘ft_rule’ was not declared in this scope
             intel_82599_five_tuple_filter_hw_rule* ft_rule;
                                                    ^
/usr/src/fastnetmon/src/fastnetmon.cpp:2955:24: error: ‘rule’ was not declared in this scope
             ft_rule = &rule.rule_family.five_tuple_rule;
                        ^
/usr/src/fastnetmon/src/fastnetmon.cpp:2958:37: error: ‘intel_82599_five_tuple_rule’ was not declared in this scope
             rule.rule_family_type = intel_82599_five_tuple_rule;
                                     ^
/usr/src/fastnetmon/src/fastnetmon.cpp:2972:36: error: ‘pf_ring_descr’ was not declared in this scope
             if (pfring_add_hw_rule(pf_ring_descr, &rule) != 0) {
                                    ^
/usr/src/fastnetmon/src/fastnetmon.cpp:2972:56: error: ‘pfring_add_hw_rule’ was not declared in this scope
             if (pfring_add_hw_rule(pf_ring_descr, &rule) != 0) {
                                                        ^
CMakeFiles/fastnetmon.dir/build.make:54: recipe for target 'CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o' failed
make[2]: *** [CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o] Error 1
CMakeFiles/Makefile2:213: recipe for target 'CMakeFiles/fastnetmon.dir/all' failed
make[1]: *** [CMakeFiles/fastnetmon.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

Best regards

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately, this code is completely broken and should not be used. 

You could create bash script and use ethttool for hardware filters management: https://github.com/FastVPSEestiOu/fastnetmon/wiki/Traffic-filtration-using-NIC-capabilities-on-wire-speed-(10GE,-14Mpps)

**Comment by pavel-odintsov** [comment]
So I could resurrect this feature if you could wait few hours :)

**Comment by pavel-odintsov** [comment]
Hello!

I have patched this code. since now it built by default. And you could enable hardware locking with option in /etc/fastnetmon.conf:
```bash
pfring_hardware_filters_enabled = off
```

**Comment by fargox** [comment]
Wow that was a fast reponse. It compiled without any issues now. Thank you very much.

**Comment by pavel-odintsov** [comment]
Welcome!
