### ISSUE TITLE
Docker image doesn't contain all necessities

### ISSUE THREAD

**Issue by coxley** [FastVPSEestiOu/fastnetmon#396]
Dockerfile doesn't install sendmail or put binaries like "notify_about_attack.sh" where the default config expects them (/usr/local/bin).

**Comment by pavel-odintsov** [comment]
Hello, Codey!

We are moving really fast and Docker file is little bit outdated.

But recently we have built binary packages for all distributions https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/PACKAGES_INSTALL.md and I would like to recommend they for running inside Docker.

If you need any help here, please ask here / in IRC or my email pavel.odintsov@gmail.com :)

**Comment by robertoberto** [comment]
Docker best practice is to separate daemons in different containers.

What we're using here to run it::


docker pull panubo/postfix

docker run \
-e MAILNAME="example.com" \
-e MYNETWORKS="127.0.0.0/8, 172.16.0.0/12" \

--name postfix \

-t panubo/postfix


docker run -a stdin -a stdout -i \

-v /var/log/fastnetmon_attacks:/var/log/fastnetmon_attacks \

-v /var/log/fastnetmon.log:/var/log/fastnetmon.log \

-v /etc/networks_list:/etc/networks_list \

-v /etc/fastnetmon.conf:/etc/fastnetmon.conf \

-v /etc/networks_whitelist:/etc/networks_whitelist \
-v /usr/local/fastnetmon:/usr/local/fastnetmon \

-v /etc/exabgp_blackhole.conf:/etc/exabgp_blackhole.conf \
-v /var/log/fastnetmon-notify.log:/var/log/fastnetmon-notify.log \

-p 10.100.20.2:2055:2055/udp \
-p 10.100.20.6:2055:2055/udp \

-p 10.100.20.2:179:179/tcp \
--name fastnetmon \

--link postfix:postfix \
-t robertoberto/fastnetmon:latest /bin/bash


We need to automate docker image using
https://docs.docker.com/docker-hub/github/. I'll rebuild image today as
requested.



2015-09-04 5:24 GMT-03:00 Pavel Odintsov <notifications@github.com>:

**Comment by coxley** [comment]
Even so, a mail binary isn't present in the image so no ability to send via remote daemon. ;)

**Comment by coxley** [comment]
@pavel-odintsov: The links for the packages in that doc aren't accurate/no longer work.

**Comment by robertoberto** [comment]
mailutils mail client need some local server to work.

When you link another container with docker other container name will be added to /etc/hosts pointing to its internal IP.
So you can use python script notify (https://github.com/robertoberto/fastnetmon/blob/master/src/scripts/fastnetmon_notify.py), instead of bash one. 

Just change MAIL_HOSTNAME="localhost" to MAIL_HOSTNAME="postfix" if you start fastnetmon docker container with --link postfix:postfix and create another docker instance with panubo/postfix as --name postfix, for example. 



Which link do you mean?

**Comment by robertoberto** [comment]
Docker image updated to latest fastnetmon revision.

**Comment by robertoberto** [comment]
I submit a merge request with new instructions https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/DOCKER_INSTALL.md

So you can close this issue as soon as merge approved.

**Comment by coxley** [comment]
Using the smtplib in Python is fine, was just saying because the default config sets the default shell script which would never work. :)

Also `hierloom-mailx` provides a mail binary which allows remote servers and as far as I can tell generally what people use. 

re: links, the .deb links in the doc that @pavel-odintsov pointed to in the first comment.

**Comment by pavel-odintsov** [comment]
Hello!

I have merged fixes from Roberto! 

@coxley what Linux distro have you used? I could build package for your OS shortly. Old packages is a bit buggy and I have remove they.

**Comment by coxley** [comment]
Ubuntu 14.04 (trusty), generally Linux 3.13.

**Comment by pavel-odintsov** [comment]
Have sent with email :)

**Comment by coxley** [comment]
Any motion toward creating a PPA at least for Ubuntu so you don't have to worry about hosting the packages, but they can still be reliably retrieved?

**Comment by pavel-odintsov** [comment]
It will be next step when we finish binary packages tests. Integration with
standart repos is really complicated because we are using bleeding edge
versions of external libs.

On Saturday, September 12, 2015, Codey Oxley <notifications@github.com>
wrote:

> Any motion toward creating a PPA at least for Ubuntu so you don't have to
> worry about hosting the packages, but they can still be reliably retrieved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/396#issuecomment-139662119>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
Could I close this ticket? Looks like after upgrade everything should work well :)
