### ISSUE TITLE
Offer different thresholds for different protocol

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#407]
So we could specify different per protocol thresholds this way:
```bash
threshold_tcp_mbps = 100000
threshold_udp_mbps = 100000
threshold_icmp_mbps = 100000

threshold_tcp_pps = 100000
threshold_udp_pps = 100000
threshold_icmp_pps = 100000

ban_for_tcp_bandwidth = off
ban_for_udp_bandwidth = off
ban_for_icmp_bandwidth = off

ban_for_tcp_pps = off 
ban_for_udp_pps = off
ban_for_icmp_pps = off
```

This option will work for host groups too. 

But please keep in mind! Global limits like threshold_mbps should be bigger than per protocol thresholds.

**Comment by zenvdeluca** [comment]
Super big thumbs up for this feature !!! :+1: :+1: :+1: :+1: :+1:

**Comment by pavel-odintsov** [comment]
You are welcome :)

**Comment by robertoberto** [comment]
Thank you Pavel! I'll start to use it soon
Em sex, 11 de set de 2015 às 15:14, Pavel Odintsov <notifications@github.com>
escreveu:

**Comment by pavel-odintsov** [comment]
Nice to see so huge interest in function :)

**Comment by zenvdeluca** [comment]
I see the ban detection / threshold at fastnetmon.log, but no ban is actually triggered.

2015-09-12 23:05:04,295 [INFO] We detected this attack by pps limit
2015-09-12 23:10:39,837 [INFO] We detected this attack by pps limit
2015-09-12 23:10:40,839 [INFO] We detected this attack by pps limit

sent my config in private

**Comment by pavel-odintsov** [comment]
So fixed!
