### ISSUE TITLE
issue with debian 7.9

### ISSUE THREAD

**Issue by gthgame** [FastVPSEestiOu/fastnetmon#410]
Hello , i'm trying to use the .pl for install on Debian 7.9 
it's return : 
This distro is unsupported, please do manual install at fastnetmon_install.pl line 864

Also i tryed to compile manualy the source. I have an error : 

root@ns205099:/usr/src/fastnetmon/src/build# cmake ..
-- Setting build type to Release as none was specified.
-- You are running Linux and we can build PF_RING support
-- We found PF_RING ZC headers and will build PF_RING ZC support
-- We have enabled PF_RING's hardware filtering option
-- We will enable nDPI support
-- We will enable LuaJIT support
-- Boost version: 1.49.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
-- We can't find hiredis library and will disable Redis support
CMake Error at CMakeLists.txt:294 (message):
  We can't find log4cpp.  We can't build project

I have liblog4cpp5-dev installed , Also note it was working few month ago with oldest version. 

Can you help me ?

**Comment by pavel-odintsov** [comment]
Hello

Could you share /etc/issue and /etc/debian_release ?

On Thursday, September 17, 2015, gthgame <notifications@github.com> wrote:

> Hello , i'm trying to use the .pl for install on Debian 7.9
> it's return :
> This distro is unsupported, please do manual install at
> fastnetmon_install.pl line 864
>
> Also i tryed to compile manualy the source. I have an error :
>
> root@ns205099:/usr/src/fastnetmon/src/build# cmake ..
> -- Setting build type to Release as none was specified.
> -- You are running Linux and we can build PF_RING support
> -- We found PF_RING ZC headers and will build PF_RING ZC support
> -- We have enabled PF_RING's hardware filtering option
> -- We will enable nDPI support
> -- We will enable LuaJIT support
> -- Boost version: 1.49.0
> -- Found the following Boost libraries:
> -- thread
> -- regex
> -- system
> -- We can't find hiredis library and will disable Redis support
> CMake Error at CMakeLists.txt:294 (message):
> We can't find log4cpp. We can't build project
>
> I have liblog4cpp5-dev installed , Also note it was working few month ago
> with oldest version.
>
> Can you help me ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/410>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by gthgame** [comment]
issue : 

------------------------------------------------------------------------------

Welcome to the Proxmox Virtual Environment. Please use your web browser to
configure this server - connect to:

  https://xx.xx.xx.xx:8006/

------------------------------------------------------------------------------


debian release : there is no file . in /etc/debian_release

but  i have : debian_version with : 

7.9

in .

**Comment by pavel-odintsov** [comment]
Could you run this command and share output and file trace.log  with me?
```bash
wget https://raw.githubusercontent.com/FastVPSEestiOu/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
sudo strace -f -s 1024 -o trace.log perl fastnetmon_install.pl --use-git-master
```

**Comment by gthgame** [comment]
Done i sent to your mail :)

**Comment by pavel-odintsov** [comment]
Fixed! :)

**Comment by gthgame** [comment]
thank you :D

**Comment by gthgame** [comment]
about the log4cpp ? it's ok if i use the auto instaler ?

**Comment by pavel-odintsov** [comment]
It's OK with automatic installer because we use custom version of log4cpp (for some weird distributions like CentOS 7 without it even in EPEL) :)

**Comment by gthgame** [comment]
nice , so i will use this :) thank you a lot for the support :) i will let you know if it's working fine. :)
