### ISSUE TITLE
Introduce attack detection algorithms

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#56]
I.E. port scan (multiple ports), netscan (multiple hosts), incoming and outgoing syn flood and other.

**Comment by franklouwers** [comment]
Might also consider keeping values for "normal" traffic for certain ip. If a host normally does 100pps, then a sudden rise to 10000pps is probably an attack (or at least worth notifying). If a host normally does 20kpps, then 40kpps is probably nothing to worry about.

**Comment by pavel-odintsov** [comment]
Very interesting idea! We could calculate average for few months per IP. But now main target of toolkit not an attack detection itself, we should detect attack which can destroy our networks.

**Comment by franklouwers** [comment]
Myes, I am more looking for a tool that abuse-desk can use. For instance, we had a compromised windows host that was DoS-ing other networks. PPS levels where at 18k pps, which is not much, but is 50 times the normal level of that host... I am hoping fastnetmon will be able to alert me of that host.

**Comment by pavel-odintsov** [comment]
Frank, I move your idea in new ticket: https://github.com/FastVPSEestiOu/fastnetmon/issues/197 And this ticket closed because I add ability to detect attack of following types: syn_flood, icmp_flood, udp_flood, ip_fragmentation_flood

**Comment by franklouwers** [comment]
:+1: :clap:
