### ISSUE TITLE
Enable issue management with Waffle

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#72]
https://waffle.io/

**Comment by pavel-odintsov** [comment]
Implemented https://waffle.io/FastVPSEestiOu/fastnetmon

**Comment by denji** [comment]
http://sweepboard.com/
https://www.blossom.co/
https://www.zenhub.io/

**Comment by pavel-odintsov** [comment]
Waffle is awesome too)
