### ISSUE TITLE
Add syn flood counter

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#87]
Subject!

**Comment by plajjan** [comment]
It would be interesting to have a ratio of SYNs going to a host and SYN-ACK coming from that host. A normal ratio would be somewhere around 1.0, give some margin for inaccuracies, especially with low traffic volume.

If the hosts themselves implement rate-limiting for SYN packets we will see an uneven ratio under an attack and could potentially use that as a trigger for detecting DDoS attacks.

**Comment by pavel-odintsov** [comment]
plajjan, I have implemented syn counter. But it's not a good idea to provide multiple counters for non critical values like acks. I trying to build strong system against attacks on channel overflow. But ack monitoring is more tight and hard challenge and should be implemented on separate server/system.

**Comment by plajjan** [comment]
You mean that having a counter for ACK would be hit too often and wouldn't bring much benefit? I get that but I am specifically looking for packets with SYN vs SYN+ACK, and you should see about as many SYN+ACK as you do SYN packets... if only ACK packet is set I don't care about it.. ;)
