### ISSUE TITLE
Exabgp integration for announce blackholed IP's with BGP

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#96]
Subject

It's more standard and reliable way to ban IPs.

**Comment by franklouwers** [comment]
could be done via for instance exabgp monitor feature, or via bird (which can learn from kernel routing tables: I have a setup on a honeypot search where fail2ban adds bad hosts to unreachable kernel routing table, and birds picks those up and blackholes them via bgp). Let me know if you need feedback/input/.. :)

**Comment by pavel-odintsov** [comment]
Could you share your experience with exabgp monitor feature? It's looks very interesting!

**Comment by pavel-odintsov** [comment]
Well, we could implement it on top of PIPE feature of exabgp: https://github.com/Exa-Networks/exabgp/issues/244

**Comment by pavel-odintsov** [comment]
Btw, we could add ability to specify community number for announce.

**Comment by s4m4n** [comment]
Best bet would be adding a bgp community to the ip and advertise it to the router. 
On the router configuration it's easy to set a policy that blackhole or null-route any received route with the community $x .

**Comment by pavel-odintsov** [comment]
Yep, so good idea. I need some time for deploying test env with Quagga.

**Comment by pavel-odintsov** [comment]
I found awesome guide for this task https://www.m00nie.com/2014/01/bgp-rtbh-setup-using-exabgp/

**Comment by pavel-odintsov** [comment]
Well, my test env have just deployed: http://www.stableit.ru/2015/04/quagga-bgp-and-exabgp-work-together-for.html

I will start my work for integration shortly.

**Comment by pavel-odintsov** [comment]
Implemented:) Testers are welcome! Reference guide here: https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/EXABGP_INTEGRATION.md
